// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/iceicelee/scooter/tools/natapp/message/ConsultMessageProtos.proto

package com.iceicelee.scooter.tools.natapp.message;

public final class ConsultMessageProto {
  private ConsultMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.msgNumber);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CSHandshakeMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.iceicelee.scooter.tools.natapp.message.CSHandshakeMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *一些客户端的信息
     * </pre>
     *
     * <code>string clientInfo = 1;</code>
     * @return The clientInfo.
     */
    java.lang.String getClientInfo();
    /**
     * <pre>
     *一些客户端的信息
     * </pre>
     *
     * <code>string clientInfo = 1;</code>
     * @return The bytes for clientInfo.
     */
    com.google.protobuf.ByteString
        getClientInfoBytes();
  }
  /**
   * Protobuf type {@code com.iceicelee.scooter.tools.natapp.message.CSHandshakeMsg}
   */
  public static final class CSHandshakeMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.iceicelee.scooter.tools.natapp.message.CSHandshakeMsg)
      CSHandshakeMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSHandshakeMsg.newBuilder() to construct.
    private CSHandshakeMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSHandshakeMsg() {
      clientInfo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CSHandshakeMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSHandshakeMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientInfo_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg.class, com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg.Builder.class);
    }

    public static final int CLIENTINFO_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientInfo_;
    /**
     * <pre>
     *一些客户端的信息
     * </pre>
     *
     * <code>string clientInfo = 1;</code>
     * @return The clientInfo.
     */
    @java.lang.Override
    public java.lang.String getClientInfo() {
      java.lang.Object ref = clientInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientInfo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *一些客户端的信息
     * </pre>
     *
     * <code>string clientInfo = 1;</code>
     * @return The bytes for clientInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientInfoBytes() {
      java.lang.Object ref = clientInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientInfo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg)) {
        return super.equals(obj);
      }
      com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg other = (com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg) obj;

      if (!getClientInfo()
          .equals(other.getClientInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getClientInfo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.iceicelee.scooter.tools.natapp.message.CSHandshakeMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.iceicelee.scooter.tools.natapp.message.CSHandshakeMsg)
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg.class, com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg.Builder.class);
      }

      // Construct using com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientInfo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_descriptor;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg getDefaultInstanceForType() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg build() {
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg buildPartial() {
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg result = new com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg(this);
        result.clientInfo_ = clientInfo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg) {
          return mergeFrom((com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg other) {
        if (other == com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg.getDefaultInstance()) return this;
        if (!other.getClientInfo().isEmpty()) {
          clientInfo_ = other.clientInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientInfo_ = "";
      /**
       * <pre>
       *一些客户端的信息
       * </pre>
       *
       * <code>string clientInfo = 1;</code>
       * @return The clientInfo.
       */
      public java.lang.String getClientInfo() {
        java.lang.Object ref = clientInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *一些客户端的信息
       * </pre>
       *
       * <code>string clientInfo = 1;</code>
       * @return The bytes for clientInfo.
       */
      public com.google.protobuf.ByteString
          getClientInfoBytes() {
        java.lang.Object ref = clientInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *一些客户端的信息
       * </pre>
       *
       * <code>string clientInfo = 1;</code>
       * @param value The clientInfo to set.
       * @return This builder for chaining.
       */
      public Builder setClientInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *一些客户端的信息
       * </pre>
       *
       * <code>string clientInfo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientInfo() {
        
        clientInfo_ = getDefaultInstance().getClientInfo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *一些客户端的信息
       * </pre>
       *
       * <code>string clientInfo = 1;</code>
       * @param value The bytes for clientInfo to set.
       * @return This builder for chaining.
       */
      public Builder setClientInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientInfo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.iceicelee.scooter.tools.natapp.message.CSHandshakeMsg)
    }

    // @@protoc_insertion_point(class_scope:com.iceicelee.scooter.tools.natapp.message.CSHandshakeMsg)
    private static final com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg();
    }

    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSHandshakeMsg>
        PARSER = new com.google.protobuf.AbstractParser<CSHandshakeMsg>() {
      @java.lang.Override
      public CSHandshakeMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSHandshakeMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSHandshakeMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSHandshakeMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.CSHandshakeMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SCHandshakeMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.iceicelee.scooter.tools.natapp.message.SCHandshakeMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *server端监听的端口 该端口的数据会被转发
     * </pre>
     *
     * <code>int32 externalPort = 1;</code>
     * @return The externalPort.
     */
    int getExternalPort();
  }
  /**
   * Protobuf type {@code com.iceicelee.scooter.tools.natapp.message.SCHandshakeMsg}
   */
  public static final class SCHandshakeMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.iceicelee.scooter.tools.natapp.message.SCHandshakeMsg)
      SCHandshakeMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SCHandshakeMsg.newBuilder() to construct.
    private SCHandshakeMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SCHandshakeMsg() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SCHandshakeMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SCHandshakeMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              externalPort_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg.class, com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg.Builder.class);
    }

    public static final int EXTERNALPORT_FIELD_NUMBER = 1;
    private int externalPort_;
    /**
     * <pre>
     *server端监听的端口 该端口的数据会被转发
     * </pre>
     *
     * <code>int32 externalPort = 1;</code>
     * @return The externalPort.
     */
    @java.lang.Override
    public int getExternalPort() {
      return externalPort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (externalPort_ != 0) {
        output.writeInt32(1, externalPort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (externalPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, externalPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg)) {
        return super.equals(obj);
      }
      com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg other = (com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg) obj;

      if (getExternalPort()
          != other.getExternalPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXTERNALPORT_FIELD_NUMBER;
      hash = (53 * hash) + getExternalPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.iceicelee.scooter.tools.natapp.message.SCHandshakeMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.iceicelee.scooter.tools.natapp.message.SCHandshakeMsg)
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg.class, com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg.Builder.class);
      }

      // Construct using com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        externalPort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_descriptor;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg getDefaultInstanceForType() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg build() {
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg buildPartial() {
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg result = new com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg(this);
        result.externalPort_ = externalPort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg) {
          return mergeFrom((com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg other) {
        if (other == com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg.getDefaultInstance()) return this;
        if (other.getExternalPort() != 0) {
          setExternalPort(other.getExternalPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int externalPort_ ;
      /**
       * <pre>
       *server端监听的端口 该端口的数据会被转发
       * </pre>
       *
       * <code>int32 externalPort = 1;</code>
       * @return The externalPort.
       */
      @java.lang.Override
      public int getExternalPort() {
        return externalPort_;
      }
      /**
       * <pre>
       *server端监听的端口 该端口的数据会被转发
       * </pre>
       *
       * <code>int32 externalPort = 1;</code>
       * @param value The externalPort to set.
       * @return This builder for chaining.
       */
      public Builder setExternalPort(int value) {
        
        externalPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *server端监听的端口 该端口的数据会被转发
       * </pre>
       *
       * <code>int32 externalPort = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalPort() {
        
        externalPort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.iceicelee.scooter.tools.natapp.message.SCHandshakeMsg)
    }

    // @@protoc_insertion_point(class_scope:com.iceicelee.scooter.tools.natapp.message.SCHandshakeMsg)
    private static final com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg();
    }

    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SCHandshakeMsg>
        PARSER = new com.google.protobuf.AbstractParser<SCHandshakeMsg>() {
      @java.lang.Override
      public SCHandshakeMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCHandshakeMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SCHandshakeMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SCHandshakeMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCHandshakeMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SCNoticeSomeOneConnectedMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.iceicelee.scooter.tools.natapp.message.SCNoticeSomeOneConnectedMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务器代理的端口，也就是他想连的端口
     * </pre>
     *
     * <code>int32 iWantPort = 1;</code>
     * @return The iWantPort.
     */
    int getIWantPort();

    /**
     * <pre>
     *我在这个端口等你来
     * </pre>
     *
     * <code>int32 connectMePort = 2;</code>
     * @return The connectMePort.
     */
    int getConnectMePort();
  }
  /**
   * Protobuf type {@code com.iceicelee.scooter.tools.natapp.message.SCNoticeSomeOneConnectedMsg}
   */
  public static final class SCNoticeSomeOneConnectedMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.iceicelee.scooter.tools.natapp.message.SCNoticeSomeOneConnectedMsg)
      SCNoticeSomeOneConnectedMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SCNoticeSomeOneConnectedMsg.newBuilder() to construct.
    private SCNoticeSomeOneConnectedMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SCNoticeSomeOneConnectedMsg() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SCNoticeSomeOneConnectedMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SCNoticeSomeOneConnectedMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              iWantPort_ = input.readInt32();
              break;
            }
            case 16: {

              connectMePort_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg.class, com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg.Builder.class);
    }

    public static final int IWANTPORT_FIELD_NUMBER = 1;
    private int iWantPort_;
    /**
     * <pre>
     *服务器代理的端口，也就是他想连的端口
     * </pre>
     *
     * <code>int32 iWantPort = 1;</code>
     * @return The iWantPort.
     */
    @java.lang.Override
    public int getIWantPort() {
      return iWantPort_;
    }

    public static final int CONNECTMEPORT_FIELD_NUMBER = 2;
    private int connectMePort_;
    /**
     * <pre>
     *我在这个端口等你来
     * </pre>
     *
     * <code>int32 connectMePort = 2;</code>
     * @return The connectMePort.
     */
    @java.lang.Override
    public int getConnectMePort() {
      return connectMePort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iWantPort_ != 0) {
        output.writeInt32(1, iWantPort_);
      }
      if (connectMePort_ != 0) {
        output.writeInt32(2, connectMePort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iWantPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iWantPort_);
      }
      if (connectMePort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, connectMePort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg)) {
        return super.equals(obj);
      }
      com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg other = (com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg) obj;

      if (getIWantPort()
          != other.getIWantPort()) return false;
      if (getConnectMePort()
          != other.getConnectMePort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IWANTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getIWantPort();
      hash = (37 * hash) + CONNECTMEPORT_FIELD_NUMBER;
      hash = (53 * hash) + getConnectMePort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.iceicelee.scooter.tools.natapp.message.SCNoticeSomeOneConnectedMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.iceicelee.scooter.tools.natapp.message.SCNoticeSomeOneConnectedMsg)
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg.class, com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg.Builder.class);
      }

      // Construct using com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        iWantPort_ = 0;

        connectMePort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_descriptor;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg getDefaultInstanceForType() {
        return com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg build() {
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg buildPartial() {
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg result = new com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg(this);
        result.iWantPort_ = iWantPort_;
        result.connectMePort_ = connectMePort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg) {
          return mergeFrom((com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg other) {
        if (other == com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg.getDefaultInstance()) return this;
        if (other.getIWantPort() != 0) {
          setIWantPort(other.getIWantPort());
        }
        if (other.getConnectMePort() != 0) {
          setConnectMePort(other.getConnectMePort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int iWantPort_ ;
      /**
       * <pre>
       *服务器代理的端口，也就是他想连的端口
       * </pre>
       *
       * <code>int32 iWantPort = 1;</code>
       * @return The iWantPort.
       */
      @java.lang.Override
      public int getIWantPort() {
        return iWantPort_;
      }
      /**
       * <pre>
       *服务器代理的端口，也就是他想连的端口
       * </pre>
       *
       * <code>int32 iWantPort = 1;</code>
       * @param value The iWantPort to set.
       * @return This builder for chaining.
       */
      public Builder setIWantPort(int value) {
        
        iWantPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器代理的端口，也就是他想连的端口
       * </pre>
       *
       * <code>int32 iWantPort = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIWantPort() {
        
        iWantPort_ = 0;
        onChanged();
        return this;
      }

      private int connectMePort_ ;
      /**
       * <pre>
       *我在这个端口等你来
       * </pre>
       *
       * <code>int32 connectMePort = 2;</code>
       * @return The connectMePort.
       */
      @java.lang.Override
      public int getConnectMePort() {
        return connectMePort_;
      }
      /**
       * <pre>
       *我在这个端口等你来
       * </pre>
       *
       * <code>int32 connectMePort = 2;</code>
       * @param value The connectMePort to set.
       * @return This builder for chaining.
       */
      public Builder setConnectMePort(int value) {
        
        connectMePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *我在这个端口等你来
       * </pre>
       *
       * <code>int32 connectMePort = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnectMePort() {
        
        connectMePort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.iceicelee.scooter.tools.natapp.message.SCNoticeSomeOneConnectedMsg)
    }

    // @@protoc_insertion_point(class_scope:com.iceicelee.scooter.tools.natapp.message.SCNoticeSomeOneConnectedMsg)
    private static final com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg();
    }

    public static com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SCNoticeSomeOneConnectedMsg>
        PARSER = new com.google.protobuf.AbstractParser<SCNoticeSomeOneConnectedMsg>() {
      @java.lang.Override
      public SCNoticeSomeOneConnectedMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCNoticeSomeOneConnectedMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SCNoticeSomeOneConnectedMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SCNoticeSomeOneConnectedMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.SCNoticeSomeOneConnectedMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int MSGNUMBER_FIELD_NUMBER = 10086;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Integer> msgNumber = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nSsrc/main/java/com/iceicelee/scooter/to" +
      "ols/natapp/message/ConsultMessageProtos." +
      "proto\022*com.iceicelee.scooter.tools.natap" +
      "p.message\032 google/protobuf/descriptor.pr" +
      "oto\"+\n\016CSHandshakeMsg\022\022\n\nclientInfo\030\001 \001(" +
      "\t:\005\260\366\004\351\007\"-\n\016SCHandshakeMsg\022\024\n\014externalPo" +
      "rt\030\001 \001(\005:\005\260\366\004\352\007\"N\n\033SCNoticeSomeOneConnec" +
      "tedMsg\022\021\n\tiWantPort\030\001 \001(\005\022\025\n\rconnectMePo" +
      "rt\030\002 \001(\005:\005\260\366\004\353\007:3\n\tmsgNumber\022\037.google.pr" +
      "otobuf.MessageOptions\030\346N \001(\005BC\n*com.icei" +
      "celee.scooter.tools.natapp.messageB\023Cons" +
      "ultMessageProtoH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iceicelee_scooter_tools_natapp_message_CSHandshakeMsg_descriptor,
        new java.lang.String[] { "ClientInfo", });
    internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iceicelee_scooter_tools_natapp_message_SCHandshakeMsg_descriptor,
        new java.lang.String[] { "ExternalPort", });
    internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iceicelee_scooter_tools_natapp_message_SCNoticeSomeOneConnectedMsg_descriptor,
        new java.lang.String[] { "IWantPort", "ConnectMePort", });
    msgNumber.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.iceicelee.scooter.tools.natapp.message.ConsultMessageProto.msgNumber);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
