// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/iceicelee/scooter/tools/natapp/message/HandshakeConsultMsg.proto

package com.iceicelee.scooter.tools.natapp.message;

public final class HandshakeConsultMsg {
  private HandshakeConsultMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CSHandshakeMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:scooter.CSHandshakeMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 port = 1;</code>
     * @return Whether the port field is set.
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 1;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code scooter.CSHandshakeMsg}
   */
  public static final class CSHandshakeMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:scooter.CSHandshakeMsg)
      CSHandshakeMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSHandshakeMsg.newBuilder() to construct.
    private CSHandshakeMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSHandshakeMsg() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CSHandshakeMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSHandshakeMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_CSHandshakeMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_CSHandshakeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg.class, com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg.Builder.class);
    }

    private int bitField0_;
    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    /**
     * <code>required int32 port = 1;</code>
     * @return Whether the port field is set.
     */
    @java.lang.Override
    public boolean hasPort() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 port = 1;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg)) {
        return super.equals(obj);
      }
      com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg other = (com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg) obj;

      if (hasPort() != other.hasPort()) return false;
      if (hasPort()) {
        if (getPort()
            != other.getPort()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code scooter.CSHandshakeMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:scooter.CSHandshakeMsg)
        com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_CSHandshakeMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_CSHandshakeMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg.class, com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg.Builder.class);
      }

      // Construct using com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_CSHandshakeMsg_descriptor;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg getDefaultInstanceForType() {
        return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg build() {
        com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg buildPartial() {
        com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg result = new com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.port_ = port_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg) {
          return mergeFrom((com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg other) {
        if (other == com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg.getDefaultInstance()) return this;
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasPort()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int port_ ;
      /**
       * <code>required int32 port = 1;</code>
       * @return Whether the port field is set.
       */
      @java.lang.Override
      public boolean hasPort() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 port = 1;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 1;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000001;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:scooter.CSHandshakeMsg)
    }

    // @@protoc_insertion_point(class_scope:scooter.CSHandshakeMsg)
    private static final com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg();
    }

    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CSHandshakeMsg>
        PARSER = new com.google.protobuf.AbstractParser<CSHandshakeMsg>() {
      @java.lang.Override
      public CSHandshakeMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSHandshakeMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSHandshakeMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSHandshakeMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.CSHandshakeMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SCHandshakeMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:scooter.SCHandshakeMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string handshakeResult = 1;</code>
     * @return Whether the handshakeResult field is set.
     */
    boolean hasHandshakeResult();
    /**
     * <code>required string handshakeResult = 1;</code>
     * @return The handshakeResult.
     */
    java.lang.String getHandshakeResult();
    /**
     * <code>required string handshakeResult = 1;</code>
     * @return The bytes for handshakeResult.
     */
    com.google.protobuf.ByteString
        getHandshakeResultBytes();
  }
  /**
   * Protobuf type {@code scooter.SCHandshakeMsg}
   */
  public static final class SCHandshakeMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:scooter.SCHandshakeMsg)
      SCHandshakeMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SCHandshakeMsg.newBuilder() to construct.
    private SCHandshakeMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SCHandshakeMsg() {
      handshakeResult_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SCHandshakeMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SCHandshakeMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              handshakeResult_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_SCHandshakeMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_SCHandshakeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg.class, com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg.Builder.class);
    }

    private int bitField0_;
    public static final int HANDSHAKERESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object handshakeResult_;
    /**
     * <code>required string handshakeResult = 1;</code>
     * @return Whether the handshakeResult field is set.
     */
    @java.lang.Override
    public boolean hasHandshakeResult() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string handshakeResult = 1;</code>
     * @return The handshakeResult.
     */
    @java.lang.Override
    public java.lang.String getHandshakeResult() {
      java.lang.Object ref = handshakeResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          handshakeResult_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string handshakeResult = 1;</code>
     * @return The bytes for handshakeResult.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHandshakeResultBytes() {
      java.lang.Object ref = handshakeResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        handshakeResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHandshakeResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, handshakeResult_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, handshakeResult_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg)) {
        return super.equals(obj);
      }
      com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg other = (com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg) obj;

      if (hasHandshakeResult() != other.hasHandshakeResult()) return false;
      if (hasHandshakeResult()) {
        if (!getHandshakeResult()
            .equals(other.getHandshakeResult())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHandshakeResult()) {
        hash = (37 * hash) + HANDSHAKERESULT_FIELD_NUMBER;
        hash = (53 * hash) + getHandshakeResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code scooter.SCHandshakeMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:scooter.SCHandshakeMsg)
        com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_SCHandshakeMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_SCHandshakeMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg.class, com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg.Builder.class);
      }

      // Construct using com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        handshakeResult_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.internal_static_scooter_SCHandshakeMsg_descriptor;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg getDefaultInstanceForType() {
        return com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg build() {
        com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg buildPartial() {
        com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg result = new com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.handshakeResult_ = handshakeResult_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg) {
          return mergeFrom((com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg other) {
        if (other == com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg.getDefaultInstance()) return this;
        if (other.hasHandshakeResult()) {
          bitField0_ |= 0x00000001;
          handshakeResult_ = other.handshakeResult_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasHandshakeResult()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object handshakeResult_ = "";
      /**
       * <code>required string handshakeResult = 1;</code>
       * @return Whether the handshakeResult field is set.
       */
      public boolean hasHandshakeResult() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string handshakeResult = 1;</code>
       * @return The handshakeResult.
       */
      public java.lang.String getHandshakeResult() {
        java.lang.Object ref = handshakeResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            handshakeResult_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string handshakeResult = 1;</code>
       * @return The bytes for handshakeResult.
       */
      public com.google.protobuf.ByteString
          getHandshakeResultBytes() {
        java.lang.Object ref = handshakeResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          handshakeResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string handshakeResult = 1;</code>
       * @param value The handshakeResult to set.
       * @return This builder for chaining.
       */
      public Builder setHandshakeResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        handshakeResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string handshakeResult = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHandshakeResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        handshakeResult_ = getDefaultInstance().getHandshakeResult();
        onChanged();
        return this;
      }
      /**
       * <code>required string handshakeResult = 1;</code>
       * @param value The bytes for handshakeResult to set.
       * @return This builder for chaining.
       */
      public Builder setHandshakeResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        handshakeResult_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:scooter.SCHandshakeMsg)
    }

    // @@protoc_insertion_point(class_scope:scooter.SCHandshakeMsg)
    private static final com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg();
    }

    public static com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SCHandshakeMsg>
        PARSER = new com.google.protobuf.AbstractParser<SCHandshakeMsg>() {
      @java.lang.Override
      public SCHandshakeMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCHandshakeMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SCHandshakeMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SCHandshakeMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.iceicelee.scooter.tools.natapp.message.HandshakeConsultMsg.SCHandshakeMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scooter_CSHandshakeMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scooter_CSHandshakeMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scooter_SCHandshakeMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scooter_SCHandshakeMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nDcom/iceicelee/scooter/tools/natapp/mes" +
      "sage/HandshakeConsultMsg.proto\022\007scooter\"" +
      "\036\n\016CSHandshakeMsg\022\014\n\004port\030\001 \002(\005\")\n\016SCHan" +
      "dshakeMsg\022\027\n\017handshakeResult\030\001 \002(\tBA\n*co" +
      "m.iceicelee.scooter.tools.natapp.message" +
      "B\023HandshakeConsultMsg"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_scooter_CSHandshakeMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_scooter_CSHandshakeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scooter_CSHandshakeMsg_descriptor,
        new java.lang.String[] { "Port", });
    internal_static_scooter_SCHandshakeMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_scooter_SCHandshakeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scooter_SCHandshakeMsg_descriptor,
        new java.lang.String[] { "HandshakeResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
